version: "3.8"

services:

  # ======================
  # DATABASES
  # ======================
  product-db:
    image: postgres:16
    container_name: product-db
    restart: always
    environment:
      POSTGRES_USER: productuser
      POSTGRES_PASSWORD: productpass
      POSTGRES_DB: productdb
    ports:
      - "5433:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
      - ./product-service/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - micro-network

  inventory-db:
    image: postgres:16
    container_name: inventory-db
    restart: always
    environment:
      POSTGRES_USER: inventoryuser
      POSTGRES_PASSWORD: inventorypass
      POSTGRES_DB: inventorydb
    ports:
      - "5434:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
      - ./inventory-service/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - micro-network

  order-db:
    image: postgres:16
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
      POSTGRES_DB: orderdb
    ports:
      - "5436:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
      - ./order-service/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - micro-network

  # ======================
  # KAFKA + ZOOKEEPER
  # ======================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - micro-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - micro-network

  # ======================
  # EUREKA SERVER
  # ======================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - micro-network

  # ======================
  # INVENTORY SERVICE
  # ======================
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: inventoryuser
      SPRING_DATASOURCE_PASSWORD: inventorypass

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - inventory-db
      - kafka
      - eureka-server
    ports:
      - "9002:9002"
    networks:
      - micro-network

  # ======================
  # ORDER SERVICE
  # ======================
  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: orderuser
      SPRING_DATASOURCE_PASSWORD: orderpass

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - order-db
      - kafka
      - eureka-server
      - inventory-service
    ports:
      - "9003:9003"
    networks:
      - micro-network

volumes:
  product_data:
  inventory_data:
  order_data:

networks:
  micro-network:
    driver: bridge
